### ISSUE TITLE
Access to input onChange event

### ISSUE THREAD

**Issue by adamtsai1** [kontrollanten/algolia-places-react#257]
I have started my own fork to convert the input into a controlled input, but in order to do this, I'd have to remove the shouldComponentUpdate returning false and I'm not sure exactly what effect this would have. Can you provide an explanation for what the purpose is for preventing component re-renders? Thanks!

**Comment by kontrollanten** [comment]
Sorry for late reply. This is just a simple React wrapper for `places.js`, which means that `algolia-places-react` only initiates `places.js` and then `places.js` is taking control over the input field. If you remove `return false` from `shouldComponentUpdate` this will lead to re-initation of `places.js`, which will cost unnecessary CPU and will reset the input value.

I've plans on rewriting `algolia-places-react` so that it's using VDOM to render (instead of places.js implementation), this will mean that I'd also need to do all the REST API requests to Algolia Places inside the component. If you've time to contribute you're welcome!

**Comment by kontrollanten** [comment]
It should now be possible to make the input controlled in the latest version with #259 

You've the `onChange` prop since before and to set the value in the input field you can use [setVal](https://community.algolia.com/places/documentation.html#api-methods-setVal) on the placesRef.

But you're still welcome to create a PR where VDOM is used instead of `places.js`.

**Comment by maiconkf** [comment]
> It should now be possible to make the input controlled in the latest version with #259
> 
> You've the `onChange` prop since before and to set the value in the input field you can use [setVal](https://community.algolia.com/places/documentation.html#api-methods-setVal) on the placesRef.
> 
> But you're still welcome to create a PR where VDOM is used instead of `places.js`.

Can you provide an example of input controlled, please?
