### ISSUE TITLE
Algolia Places React don't work

### ISSUE THREAD

**Issue by JeremyMeissner** [kontrollanten/algolia-places-react#318]
Hi, when I install the package with npm I have this errors
```
macbook-pro-de-alexis:Baoba alexismeissner$ sudo npm install algolia-places-react --save
Password:
+ algolia-places-react@1.5.0
added 19 packages from 21 contributors and audited 37706 packages in 7.607s
found 11 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```
```
macbook-pro-de-alexis:Baoba alexismeissner$ sudo npm audit fix
up to date in 4.139s
fixed 0 of 11 vulnerabilities in 37706 scanned packages
 11 vulnerabilities required manual review and could not be updated
```
And when I insert `import AlgoliaPlaces from 'algolia-places-react';` on my App I have this error on my phone: `undefined is not and object (evaluating 'document.createElement')`

Thanks you !

**Comment by kontrollanten** [comment]
Regarding the `npm install` output it's only warnings, no errors.

Regarding `undefined is not an object` I'd guess it's not related to this package since we're not doing any "document.createElement". Without any trace log it's hard to tell where the problem lies. Please re-open if you find it necessary.
